id: 169aaa050b0047b3a3d54ae9dabe3722
initial_creation_type: ocr
source_metadata:
  volumes:
    b18249475fec4db68c2e68e589940a7b:
      base_file: v091.txt
      image_group_id: I1PD95937
      title: ''
      total_pages: 1728
      volume_number: 92
