id: D5EF5D885
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:13:52+00:00'
last_modified: '2022-05-30T03:57:59.807630+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a446:
      image_group_id: I1PD95937
      title: འདུལ་བ་མདོའི་རྣམ་པར་བཤད་པ།
      total_pages: 1728
      order: 92
      base_file: a446.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
